sudo: required
services:
    - docker
before_install:
    - docker build -t mohamedthowbick/docker-react -f Dockerfile.dev .
script:
    - docker run mohamedthowbick/docker-react npm run test -- --coverage