sudo: required
services:
  - docker
before_install:
  - docker build -t mohamedthowbick/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true mohamedthowbick/docker-react npm run test
deploy:
  - provider: elasticbeanstalk
  - region: "ap-southeast-1"
  - app : "docker-react"
  - environment: "DockerReact-env"
  - bucket_name: "elasticbeanstalk-ap-southeast-1-629830000026"
  - bucket_path: "docker-react"
  on
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"