sudo: required
services:
    - docker
before_install:
    - docker build -t mohamedthowbicl/docker-react -f Dockerfile.dev .
script:
    - docker run mohamedthowbicl/docker-react npm run test -- --coverage